import 'package:get_it/get_it.dart';
import 'package:pozitive/Core/Model/dashBoardDetailsDataModel.dart';
import 'package:pozitive/Core/Model/user.dart';
import 'package:pozitive/Core/Services/GroupQuoteNotesApi.dart';
import 'package:pozitive/Core/Services/changePasswordApi.dart';
import 'package:pozitive/Core/Services/database.dart';
import 'package:pozitive/Core/Services/forgotPasswordApi.dart';
import 'package:pozitive/Core/Services/logInApi.dart';
import 'package:pozitive/Core/Services/profileApi.dart';
import 'package:pozitive/Core/Services/quotationNoteApi.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/GenerateContractIndividualViewModel.dart';
import 'package:pozitive/Core/ViewModel/PartnerSavePriceWithUpLiftViewModel.dart';
import 'package:pozitive/Core/ViewModel/changePasswordViewModel.dart';
import 'package:pozitive/Core/ViewModel/commission_statement_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/daily_commission_report_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/dashboardViewModels/dashboard_list_item_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/forgotPasswordViewModel.dart';
import 'package:pozitive/Core/ViewModel/individualgroup_view_note_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/home_page_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/logInProvider.dart';
import 'package:pozitive/Core/ViewModel/profileProvideModel.dart';
import 'package:pozitive/Pages/Quotation/GenerateContract/generateContractIndividual.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/electricity_one_year_viewmodel.dart';
import 'Model/request_quote_history_button_model.dart';
import 'Model/request_quote_history_model.dart';
import 'Model/request_quote_viewbutton_model.dart';
import 'package:pozitive/Core/ViewModel/EleAddProspectViewModels/ele_business_viewmodel.dart';
import 'Services/AddQuoteQuickLeadService.dart';
import 'Services/navigation_service.dart';
import 'ViewModel/Add_QuoteQuickLead_ViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/PrimaryContactViewModel.dart';
import 'ViewModel/EleAddProspectViewModels/PrimaryContactViewModel.dart';
import 'ViewModel/ExportTenderServiceViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/PrimaryContactViewModel.dart';
import 'ViewModel/Group-Quotation/group_quotation/TemplateGroupQuoteViewModel.dart';
import 'ViewModel/Group-Quotation/group_quotation/group_quotation_tab_viewmodel.dart';
import 'ViewModel/Group-Quotation/group_quotation/quotation_group_viewmodel.dart';
import 'ViewModel/Group-RefreshRequote-ViewModel.dart';
import 'ViewModel/Group-addViewNoteModel.dart';
import 'ViewModel/Group-Quotation/GroupAddPartnerAddQuickLeadQuoteViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/InsertAddProspect-viewModel.dart';
import 'ViewModel/addAndViewNoteViewModel.dart';
import 'ViewModel/dashBoardDetailsViewModel.dart';
import 'ViewModel/group-view_note_viewModel.dart';
import 'ViewModel/ViewRequestQuoteViewModels/ViewQuotationPageViewModel.dart';
import 'ViewModel/group_quotation_viewmodel.dart';
import 'Model/ask_for_requote_group_model.dart';
import 'ViewModel/Group-Quotation/ask_for_requote_group_viewModel.dart';
import 'ViewModel/Group-Quotation/email_tender_price_group_viewmodel.dart';
import 'Model/email_tender_price_group_model.dart';
import 'Model/request_quote_history_group_model.dart';
import 'ViewModel/Group-Quotation/request_quote_history_group_viewmodel.dart';
import 'ViewModel/Group-Quotation/quote_history_dropdown_group_viewmodel.dart';
import 'Model/quote_history_dropdown_group_model.dart';
import 'ViewModel/EleAddProspectViewModels/ele_ele_viewmodel.dart';
import 'ViewModel/EleAddProspectViewModels/ele_siteAddress_viewmodel.dart';
import 'ViewModel/EleAddProspectViewModels/ele_billAddress_viewmodel.dart';
import 'ViewModel/EleAddProspectViewModels/ele_energy_account_manager_viewmodel.dart';
import 'ViewModel/EleAddProspectViewModels/ele_payment_viewmodel.dart';
import 'ViewModel/EleAddProspectViewModels/ele_partner_viewmodel.dart';
import 'ViewModel/EleAddProspectViewModels/ele_group_viewmodel.dart';
import 'ViewModel/quotation_page/gas_price_one_viewmodel.dart';
import 'ViewModel/quotation_page/price_electricity_gas_viewmodel.dart';
import 'ViewModel/quotation_page/quotation_electricity_viewmodel.dart';
import 'ViewModel/quotation_page/quotation_gas_viewmodel.dart';
import 'ViewModel/quotation_page/quotation_invidual_viewmodel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/gasDualFuelAddProspectViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/DualFuelBusiness-ViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/siteAddressDualFuel-viewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/billingAddress-ViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/PaymentDuelFuel-ViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/AccountManagerDualFuel-ViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/DFGroupViewModel.dart';
import 'ViewModel/DualFuelAddProspect-viewModel/DualFuelPartnerViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasGasViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasBusinessViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasSiteAddViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasBillAddViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasEAMViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasPaymentViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasPartnerViewModel.dart';
import 'ViewModel/GasAddProspectViewModel/GasGroupViewModel.dart';
import 'ViewModel/ViewRequestQuoteViewModels/ViewRequestQuoteIndividualViewmodel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/UniqueRefNoViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/BusinessDetailViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/SiteAddressViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/ElectricityViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/GasViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/DirectDebitAgreementViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/BillingAddressViewModel.dart';
import 'package:pozitive/Core/ViewModel/quotation_page/IndividualContractViewModels/EAMViewModel.dart';
import 'package:pozitive/Core/ViewModel/QuoteHistoryIndividualViewModel.dart';
import 'package:pozitive/Core/ViewModel/Group-Quotation/GroupAskForQuoteNewViewModel.dart';
import 'package:pozitive/Core/ViewModel/Group-Quotation/preview_page_group_view_model.dart';
import 'package:pozitive/Core/ViewModel/Group-Quotation/group_quotation/group_detail_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/Group-Quotation/price_elec_gas_group_rq_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/view_group_quotation_viewmodels/view_group_quotation_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/Group-Quotation/group_quotation/view_group_details_viewmodel.dart';
import 'package:pozitive/Core/ViewModel/Group-Quotation/view_price_elec_gas_viewmodel.dart';

GetIt getIt = GetIt.instance;

void setupGetIt() {
  // Firebase

  getIt.registerLazySingleton(() => LogInApi());
  getIt.registerLazySingleton(() => NavigationService());
  getIt.registerFactory(() => DatabaseImplementation());
  getIt.registerLazySingleton(() => ProfileApi());
  getIt.registerLazySingleton(() => LogInModel());
  //getIt.registerLazySingleton(() => DashBoardApi());
  getIt.registerLazySingleton(() => ForgotPasswordApi());
  getIt.registerLazySingleton(() => ProfileProviderModel());
  getIt.registerLazySingleton(() => ForgotPasswordViewModel());
  getIt.registerLazySingleton(() => ChangePasswordAPi());
  getIt.registerLazySingleton(() => ChangePasswordViewModel());
  getIt.registerLazySingleton(() => DashBoardDetailDataModel());
  getIt.registerLazySingleton(() => DashBoardDetailsViewModel());
  getIt.registerLazySingleton(() => AddandViewNoteViewModel());
  getIt.registerLazySingleton(() => AskForRequoteGroupModel());
  getIt.registerLazySingleton(() => RequestQuoteHistoryModel());
  getIt.registerLazySingleton(() => RequestQuoteHistoryButtonModel());
  getIt.registerLazySingleton(() => RequestQuoteViewButtonModel());
  getIt.registerLazySingleton(() => EmailTenderPriceGroupModel());
  getIt.registerLazySingleton(() => RequestQuoteHistoryGroupModel());
  getIt.registerLazySingleton(() => QuoteHistoryDropDownGroupModel());
  getIt.registerLazySingleton(() => QuotationNoteApi());
  getIt.registerFactory(() => User());
  getIt.registerFactory(() => CommissionStatementViewModel());
  getIt.registerFactory(() => DailyCommissionReportViewModel());
  getIt.registerFactory(() => AddQuickLeadViewModel());
  getIt.registerFactory(() => AddQuickQuoteLeadService());
  getIt.registerFactory(() => HomePageViewModel());
  getIt.registerFactory(() => DashBoardItemViewModel());
  getIt.registerFactory(() => GroupQuotationTabViewModel());
  getIt.registerFactory(() => GroupViewNoteViewModel());
  getIt.registerFactory(() => GroupsAddandViewNoteViewModel());
  getIt.registerFactory(() => GroupsViewNoteViewModel());
  getIt.registerFactory(() => GroupQuotationNoteApi());
  getIt.registerFactory(() => PartnerSavePriceUpLiftViewModel());
  getIt.registerFactory(() => ExportTenderPriceViewModel());
  getIt.registerFactory(() => GroupRefreshReQuotedViewModel());
  getIt.registerFactory(() => GroupAddPartnerAddQuickLeadQuoteViewModel());
  getIt.registerFactory(() => QuotationIndividualViewModel());
  getIt.registerFactory(() => QuotationElectricityViewModel());
  getIt.registerFactory(() => QuotationGasViewModel());
  getIt.registerFactory(() => PriceElectricityGasViewModel());
  getIt.registerFactory(() => GasPriceOneViewModel());
  getIt.registerFactory(() => AskForRequoteGroupViewModel());
  getIt.registerFactory(() => EmailTenderPriceGroupViewModel());
  getIt.registerFactory(() => RequestQuoteHistoryGroupViewModel());
  getIt.registerFactory(() => QuoteHistoryDropDownGroupViewModel());
  getIt.registerFactory(() => ElectricityOneYearViewModel());
  getIt.registerFactory(() => EleEleAddProspectViewModel());
  getIt.registerFactory(() => EleBusAddProspectViewModel());
  getIt.registerFactory(() => EleSiteAddressAddProspectViewModel());
  getIt.registerFactory(() => EleBillAddressAddProspectViewModel());
  getIt.registerFactory(() => EleEAMAddProspectViewModel());
  getIt.registerFactory(() => ElePaymentAddProspectViewModel());
  getIt.registerFactory(() => ElePartnerAddProspectViewModel());
  getIt.registerFactory(() => EleGroupAddProspectViewModel());
  getIt.registerFactory(() => DualFuelAddProspectViewModel());
  getIt.registerFactory(() => DualFuelGasAddProspectViewModel());
  getIt.registerFactory(() => DualFuelAddProspectBusinessViewModel());
  getIt.registerFactory(() => DualFuelSiteAddressAddProspectViewModel());
  getIt.registerFactory(() => DualFuelBillingAddressAddProspectViewModel());
  getIt.registerFactory(() => PaymentDuelFuelViewModel());
  getIt.registerFactory(() => AccountManagerDualFuelViewModel());
  getIt.registerFactory(() => DFGroupViewModel());
  getIt.registerFactory(() => DualFuelPartnerAddProspectViewModel());
  getIt.registerFactory(() => GasGasAddProspectViewModel());
  getIt.registerFactory(() => GasBusinessAddProspectViewModel());
  getIt.registerFactory(() => GasSiteAddAddProspectViewModel());
  getIt.registerFactory(() => GasBillAddAddProspectViewModel());
  getIt.registerFactory(() => GasEAMAddProspectViewModel());
  getIt.registerFactory(() => GasPaymentAddProspectViewModel());
  getIt.registerFactory(() => GasPartnerAddProspectViewModel());
  getIt.registerFactory(() => GasGroupAddProspectViewModel());
  getIt.registerFactory(() => QuotationGroupViewModel());
  getIt.registerFactory(() => ViewRequestQuoteIndividualViewModel());
  getIt.registerFactory(() => ViewRequestQuoteViewModel());
  getIt.registerFactory(() => TemplateQuotationGroupViewModel());
  getIt.registerFactory(() => GenerateContractIndividual());
  getIt.registerFactory(() => GenerateContractIndividualViewModel());
  getIt.registerFactory(() => UniqueRefNoViewModel());
  getIt.registerFactory(() => BusinessDetailViewModel());
  getIt.registerFactory(() => SiteAddressViewModel());
  getIt.registerFactory(() => ElectricityViewModel());
  getIt.registerFactory(() => GasViewModel());
  getIt.registerFactory(() => DirectDebitAgreementViewModel());
  getIt.registerFactory(() => BillingAddressViewModel());
  getIt.registerFactory(() => EAMViewModel());
  getIt.registerFactory(() => QuoteHistoryIndividualViewModel());
  getIt.registerFactory(() => GroupQuotationViewModel());
  getIt.registerFactory(() => DFPrimaryContactViewModel());
  getIt.registerFactory(() => GasPrimaryContactViewModel());
  getIt.registerFactory(() => ElePrimaryContactViewModel());
  getIt.registerFactory(() => GroupQuotationTabViewModelNew());
  getIt.registerFactory(() => PreviewPageGroupViewModel());
  getIt.registerFactory(() => GroupDetailsTabViewModel());
  getIt.registerFactory(() => PriceElecGasGroupRQViewModel());
  getIt.registerFactory(() => ViewGroupQuotationViewModel());
  getIt.registerFactory(() => ViewGroupDetailViewModel());
  getIt.registerFactory(() => ViewPriceElectricityGasViewModel());
}
